### PR TITLE
Fix the batch connect logic for hooks

### LINKED ISSUE #2729: [Bug] FOSSBilling registers *every* static function as a hook listener
### Describe the bug

Whenever the cron jobs are run, FOSSBilling looks for event listeners to register and saves them to the `extension_meta` table.

It should only register listening functions, not *every* static function in existence.

### How to reproduce

1- Run the cron jobs to connect the hooks.
2- Run the following query:
```sql
SELECT * FROM `extension_meta` WHERE extension = "mod_hook";
```
3- Notice that there are hundreds of listeners registered.

### Expected behavior

It should only register actual listeners.

### Additional context

https://github.com/FOSSBilling/FOSSBilling/blob/a3f51f10808a38bc8ca8024e57fedd7a3dbca2ef/src/modules/Hook/Service.php#L99-L114

### PR DESCRIPTION
**Pull request by BelleNottelling**
Closes #2729 by fixing the logic for hook connections and added a solution to remove anything that was registered when it wasn't really a hook

### CODE REVIEW

File: src/modules/Hook/Service.php [hunk 1]
```diff
@@ -195,15 +202,17 @@ private function _disconnectUnavailable()
...
                     $this->di['db']->exec($rm_sql, ['id' => $listener['id']]);
-
-                    continue;
                 }
 
-                $s = $mod->getService();
-                if (!method_exists($s, $event)) {
+
+                // If the listener is for a module that's not installed and is **not** a core module, remove the listener
+                $ext = $this->di['db']->findOne('extension', "type = 'mod' AND name = :mod AND status = 'installed'", ['mod' => $mod_name]);
```
Comment (yagiz-dev) [inline src/modules/Hook/Service.php:214]: Great work and everything LGTM.

Unrelated to your PR but can't we pull the list of installed modules once instead of querying again for every module?

**Review by j-a-pope — APPROVED** [review]

**Review by evrifaessa — APPROVED** [review]

File: src/modules/Hook/Service.php (hunk 1 above)
Comment (BelleNottelling) [reply src/modules/Hook/Service.php:214]: I'm not sure what you mean?

In the `_disconnectUnavailable` function we don't have a complete list of modules, only a list of listeners
