### PR TITLE
Opt-in error reporting via Sentry.io

### LINKED ISSUE #1730: Opt-in error logging and tracking
We should look into options for adding opt-in error reporting for FOSSBilling.

[Sentry.io](https://sentry.io/welcome/) looks to be a great option as it'll allow us to easily add in error logging, offers the ability to collect performance metrics, and comes with a bunch of other really great features like:
- Tracking releases & health: Allowing us to easily identify if a new release introduces a regression in stability, see adoption rate, and track the overall stability of the progress over time
- Built-in tools to scrub any sensitive information to ensure nothing is being logged
- [Certified compliance](https://sentry.io/security/) in terms of security, data handling, and privacy practices
- Data filtering tools
- Great customization
- Just generally a great dashboard to allow us to easily find, filter, sort, and understand the data that's being collected.

If implemented correctly something like Sentry improve our ability to resolve common problems in FOSSBilling and improve the stability of it quickly and easily.

Additionally and counter-intuitively, adding in the additional logging metrics through sentry would *improve* the privacy of FOSSBilling administrators and their clients as rather than needing someone to share an error log which may potentially leak private information, we would instead only need to know the `server_name` that's set for a given install with the Sentry SDK.
Having that would allow us to find errors reported through the dashboard, including more information than what would be found in a standard error log. That info will already be scrubbed of sensitive data and by using the sentry implementation wherever possible, it can reduce the frequency at which someone shares an error log publicly without validating if it may contain sensitive information.

I will experiment with a Sentry implementation and submit a PR if I create what I consider to be a good implementation of it, but if others have any suggestion for other tools that can be used, I'd be happy to hear it

### PR DESCRIPTION
**Pull request by BelleNottelling**
Closes #1730.

This pull request implements opt-in automated error reporting via Sentry.io.
Everything is fully documented, I've gone through and prevented some exceptions we certainly don't want to see from being reported, and done quite a bit of under-the-hood changes to exceptions and error handling in FOSSBilling to clean up various rough-edges.

Both the Sentry SDK and the Sentry.io server will automatically scrub sensitive information (such as PII), but we can at any time add to this list if we discover something that's not already being scrubbed.

Our Sentry.io organization is configured to require this scrubbing to be enabled on all projects **including** IP address scrubbing.

## Changes to error handling
- PHP's error handling is now completely disabled as FOSSBilling already logged items, resulting in duplicated log entries.
- I've cleaned up and improved the actual error logging in FOSSBilling so that the messages are clearer and more informative.
- `Box_Exception` has been replaced with `FOSSBilling\Exception` and temporarily acts as an alias to it.
- I have added a new `FOSSBilling\InformationException` class which is intended for use with informational exceptions, such as informing the user a product is out of stock or that their password isn't strong enough. These will not be reported to Sentry.io and I have updated roughly 200 exceptions inside of FOSSBilling to use this new class.
- Both error pages will show the newly introduced instance ID to aid in troubleshooting.
- Some various changes under-the-hood to streamline the integration with Sentry.io.
- Changes to the config structure.

## Error-reporting specific changes / additions
- We can exclude errors from being reported via the `\FOSSBillingErrorPage` class now.
- The installer now has an optional selection for error reporting, and some basic info on it with links to the documentation where things are explained in more detail.
- I've added in a new "instance ID" system which is very basic. More info is in a below header.
- Sentry.io is now integrated (duh!).
- The bug report form now asks for the instance ID, though I didn't make it a requirement since error-reporting is opt-in and otherwise the ID is of no help for us.
- The system settings page now includes the instance ID under "about" and there's a new tab for error reporting.
- There are now two new messages that will displayed after an update. One for old installs that didn't support error reporting and another for if we change the behavior of error reporting. (See the screenshots for these)
- Our build workflow adds in the Sentry DSN, so preview builds and releases should already have it included. This step is only run on our own repo or on PRs that are from our repo.

## What is reported

(This is just a copy & paste from the docs PR, which also means we have this listed for system administrators to see)

- Information about the request such as the request headers and URL being request.
- The PHP version in use.
- All types of errors that may occur in PHP applications (This does not include anything sent via `error_log`).
- Exceptions thrown within FOSSBilling (with some exceptions for informational exceptions).
- The version of FOSSBilling that's in use.
- The unique instance ID for your FOSSBilling install.
- If we are able to detect it, what type of web-server that's being used.
- Error-specific information such as the path where it occurred and the stacktrace that led to the error.
- Information about the host server such as it's hostname, operating system, and OS version information.

### FOSSBillng

image
image
image
image
image
image
image

### Sentry.io

image
image

## FOSSBilling instance IDs

This pull request will implement a very simple system to give each FOSSBilling instance a unique ID.
These IDs are RFC4122 version 4 UUIDs which are randomly generated and have an insanely low chance of collisions.

Instance IDs are stored in the config file under `info`->`instance_id`.

The instance ID is passed along to Sentry.io, so it can be used within the dashboard to track or filter issues for a specifically installed instance. I have also added a prompt to our bug report form to request this.

By having these IDs sent via bug reports, we will be able to efficient find captured errors for a given instance, look up stack traces, and even get basic info on the environment that is being used without needing to have back-and-forth conversations with the reporter. Historically it can be rather difficult to get this type of info from some people (either because they are lazy or don't understand) so hopefully being able to get all of that after only being given the instance ID will eliminate some pain points that can occur when trying to provide support.

Instance IDs are found both in the system settings and on the error page.

## Error filtering and capturing

All PHP errors and exceptions are recorded excluding anything sent via `error_log` and what's listed below:

### Errors that aren't reported
 - Errors in the FOSSBilling loader (these are almost exclusively issues specific to a given install)
 - `2001`: Incomplete server manager configurations.
 - `3001`: Incomplete domain registrar configurations.
 - `4001`: Incomplete payment gateway configurations.
 - `InformationException` exception classes are ignore as they are intended to be informational only (IE: "This product is out of stock") (I have changed ~200 of our exceptions to be this).
 - Errors marked to not be reported via the `ErrorPage` class.

### Significant / breaking changes
 - All new `FOSSBilling\Exception` and `FOSSBilling\InformationException` exception classes. `Box_Exception` is temporarily aliased to `FOSSBilling\Exception`and our internal code has been adjusted to reference the new classes.
 - Modifications to the config layout regarding debug options. This change was done to make this a bit cleaner by grouping related items under a `debug_and_monitoring` key.
 - The `salt` config key has been moved under `info` rather than having no parent key name.

### CODE REVIEW

**Comment by BelleNottelling** [comment]
This PR is now ready to be reviewed and tested. The PR for the documentation should also be reviewed: https://github.com/FOSSBilling/fossbilling.org/pull/165

Here's a zip with a build that has the DSN configured for error reporting, the preview zip off of the action on GH won't include it:
[FOSSBilling - Error Reporting.zip](https://github.com/FOSSBilling/FOSSBilling/files/13108208/FOSSBilling.-.Error.Reporting.zip)

**Review by jaapmarcus — APPROVED** [review]

**Comment by BelleNottelling** [comment]
I've attached the most up-to-date preview of the error reporting build here:
[FOSSBilling Error Reporting RC2.zip](https://github.com/FOSSBilling/FOSSBilling/files/13170894/FOSSBilling.Error.Reporting.RC2.zip)

File: src/library/FOSSBilling/CentralAlerts.php [hunk 1]
```diff
@@ -42,7 +42,7 @@ public function getDi(): ?Container
      * The alerts are **never** displayed to the clients.
      *
      * @return array The alerts
-     * @throws \Box_Exception
+     * @throws Exception
```
Comment (admdly) [inline src/library/FOSSBilling/CentralAlerts.php:45]: Should be `@throws \FOSSBilling\Exception`, no?

File: src/library/FOSSBilling/CentralAlerts.php [hunk 2]
```diff
@@ -62,7 +62,7 @@ public function getAlerts(): array
      * @param string $version The version to filter by (e.g. 0.4.2) - defaults to the current version of FOSSBilling
      *
      * @return array The filtered alerts
-     * @throws \Box_Exception
+     * @throws Exception
```
Comment (admdly) [inline src/library/FOSSBilling/CentralAlerts.php:65]: `@throws \FOSSBilling\Exception`?

File: src/library/FOSSBilling/CentralAlerts.php [hunk 3]
```diff
@@ -95,7 +95,7 @@ public function filterAlerts(array $type = [], string $version = Version::VERSIO
      * @param array $params The array of parameters to pass to the API endpoint
      *
      * @return array The API response
-     * @throws \Box_Exception
+     * @throws Exception
```
Comment (admdly) [inline src/library/FOSSBilling/CentralAlerts.php:98]: `@throws \FOSSBilling\Exception`?

File: src/library/FOSSBilling/CentralAlerts.php (hunk 1 above)
Comment (BelleNottelling) [reply src/library/FOSSBilling/CentralAlerts.php:45]: Depends on how you look at it.
Because these files are under the FOSSBilling namespace, `Exception` is actually the FOSSBilling exception class and `\Exception` would be the default PHP exception class. When moused over, my IDE correctly identified it as the FOSSBilling version as well.

If it's confusing I can change it, though

Comment (admdly) [reply src/library/FOSSBilling/CentralAlerts.php:45]: I'm OK either way, though given the risk of confusion with `\Exception` it may be an idea to clarify for those quickly glancing at  thecode. In other cases where there is no potential confusion, then certainly agree about not needing to specify the namespace.

I mainly noticed as it is specified as `\FOSSBilling\Exception` in other reviewed files, so more of a consistency issue. So I guess more of a let's pick one way going forward and stick with it?

File: src/library/FOSSBilling/Instance.php
Comment (admdly) [inline src/library/FOSSBilling/Instance.php:1]: Copied from Discord #chat:

> RE: #1732 - out of interest, what guarantees are being provided with regard to instance ID? I see it stated they aren't reversible, which is true, but it would be possible to confirm a URL = instance ID as implemented.
>
> Not a huge issue, but generating a theoretical rainbow table for millions/billions of URLs wouldn't be too difficult. Similarly, a fresh install on the same URL would use the same instance ID - whereas I'd (personally) expect the instance ID to be instance/install specific.

I understand the logic behind using UUIDv5, in that the results (given a known namespace) are determenistic - however we don't really require this property, and indeed it may not even ideal for the reasons mentioned above. 

Personally, I'd be tempted to go with a random UUID generated at install (perhaps stored in `config.php`?) that wouldn't have the same potential downsides. However, you know the implementation of this better, so I'm curious what your thoughts are. 🙂

File: src/library/FOSSBilling/CentralAlerts.php (hunk 1 above)
Comment (BelleNottelling) [reply src/library/FOSSBilling/CentralAlerts.php:45]: Well that consistency difference is because the files outside of our library aren't namespaced under FOSSBilling.

I can either update those to add in a use statement for the `\FOSSBilling\Exception` class or adjust the library to reference the full class name to resolve that

Comment (admdly) [reply src/library/FOSSBilling/CentralAlerts.php:45]: > Well that consistency difference is because the files outside of our library aren't namespaced under FOSSBilling.
> 
> I can either update those to add in a use statement for the `\FOSSBilling\Exception` class or adjust the library to reference the full class name to resolve that

I see no reason to change files outside of the namespace for this - consistency within the namespace is fine with me. 

For example, I can briefly see `FOSSBilling\ExtensionManager.php`, `FOSSBilling\Update.php`, `FOSSBilling\Validate.php`, and `FOSSBilling\i18n.php using both forms interchangably.

File: src/library/FOSSBilling/Instance.php
Comment (BelleNottelling) [reply src/library/FOSSBilling/Instance.php:1]: > RE: https://github.com/FOSSBilling/FOSSBilling/pull/1732 - out of interest, what guarantees are being provided with regard to instance ID? I see it stated they aren't reversible, which is true, but it would be possible to confirm a URL = instance ID as implemented.
>
>Not a huge issue, but generating a theoretical rainbow table for millions/billions of URLs wouldn't be too difficult.

In this case, I wanted a simple way to get an identifier that wouldn't potentially have duplicates and using the URL would be a really easy way to do this as someone can't have two functional installations of FOSSBilling at the same URL.

The other thing I wanted was for people to be able to get support without handing out their URL as I recognize some companies may build out a completely custom interface, remove all references to FOSSBilling, and then not publicly announce that's what they are using for their billing platform and if they had to share their URL via a GitHub report it would detract from that wish.

Practically speaking, we are generally talking about installations that are expected to be publicly accessible so I don't see reason to worry about people generating and then testing millions or even billions of URLs to try and brute-force match an ID to a URL. I think that's just a bit ridiculous and unless someone publicly posts information that would make their installation easily compromised, I don't especially see any kind of security concern with it.

I also think that having error reporting is going to help decrease the chances of sharing info that may lessen the security of their installation as those reports are going to have restricted access around them and properly using it actively reduces the need for people to give us information.

> Personally, I'd be tempted to go with a random UUID generated at install (perhaps stored in config.php?) that wouldn't have the same potential downsides. However, you know the implementation of this better, so I'm curious what your thoughts are. 🙂

I am fine with this. The most important thing to me is that the IDs are for sure not going to accidentally be duplicated because the moment that happens, we can no longer effectively rely on just that ID being enough for us to pull up errors & info that are specific to that persons installation. That's why I went with UUIDv5 IDs with the URLs as they are deterministic.

We may also do a bit of a hybrid approach and continue to use the URL, but introduce a random namespace / salt that's created during installation. That would then mean things can't be brute-forced and that each new install would get a new ID. 
Even if a namespace got duplicated, it wouldn't matter and there still wouldn't be an accidental duplication of IDs because the URLs on their own already ensures no accidental duplication.

File: src/library/FOSSBilling/CentralAlerts.php (hunk 1 above)
Comment (BelleNottelling) [reply src/library/FOSSBilling/CentralAlerts.php:45]: Ah - That's just a mistake because I didn't catch all of them.
I've corrected the mentioned files now, thanks for the catch

File: src/library/FOSSBilling/Instance.php
Comment (admdly) [reply src/library/FOSSBilling/Instance.php:1]: > Practically speaking, we are generally talking about installations that are expected to be publicly accessible so I don't see reason to worry about people generating and then testing millions or even billions of URLs to try and brute-force match an ID to a URL. I think that's just a bit ridiculous and unless someone publicly posts information that would make their installation easily compromised, I don't especially see any kind of security concern with it.

I agree it's not the most likely scenario, however an attack may not be quite so complicated if targeted. For example, if someone was to gain access to the Sentry data (via whatever means) it would only take seconds to find all reports related to a particular URL known to be running FOSSBilling (or even the reports for every known FOSSBilling install URL, as it would take seconds/minutes to generate them all).

> I also think that having error reporting is going to help decrease the chances of sharing info that may lessen the security of their installation as those reports are going to have restricted access around them and properly using it actively reduces the need for people to give us information.

Agree with this completely.

> I am fine with this. The most important thing to me is that the IDs are for sure not going to accidentally be duplicated because the moment that happens, we can no longer effectively rely on just that ID being enough for us to pull up errors & info that are specific to that persons installation. That's why I went with UUIDv5 IDs with the URLs as they are deterministic.
> 
> We may also do a bit of a hybrid approach and continue to use the URL, but introduce a random namespace / salt that's created during installation. That would then mean things can't be brute-forced and that each new install would get a new ID. Even if a namespace got duplicated, it wouldn't matter and there still wouldn't be an accidental duplication of IDs because the URLs on their own already ensures no accidental duplication.

I am perfectly happy with either approach, as they solve the issues raised. UUIDv4 is, I understand, practically unique and I highly doubt we would ever run into collisions at our scale. However, to further reduce the risk UUIDv5 with a unique namespace also works for me. 🙂

File: src/library/FOSSBilling/UpdatePatcher.php [hunk 4]
```diff
@@ -156,7 +159,7 @@ private function executeSql($sql): void
         $statement = $this->di['pdo']->prepare($sql);
         try {
             $statement->execute();
-        } catch (\Box_Exception $e) {
+        } catch (\FOSSBilling\Exception $e) {
```
Comment (admdly) [inline src/library/FOSSBilling/UpdatePatcher.php:162]: Just one... or two left. 😉

File: src/library/FOSSBilling/Validate.php [hunk 5]
```diff
@@ -80,22 +80,22 @@ public function isPasswordStrong($pwd) : bool
      * @param array $data - Array to search for keys
      * @param array $variables - Array of variables for message placeholders (:placeholder)
      * @param integer $code - Exception code
-     * @throws \Box_Exception
+     * @throws \FOSSBilling\InformationException
```
Comment (admdly) [inline src/library/FOSSBilling/Validate.php:83]: ... and this is the two. 😁

File: src/library/FOSSBilling/UpdatePatcher.php (hunk 4 above)
Comment (BelleNottelling) [reply src/library/FOSSBilling/UpdatePatcher.php:162]: sddefault

Comment (BelleNottelling) [reply src/library/FOSSBilling/UpdatePatcher.php:162]: Actually.. I think this one is just outright an error. This should be catching any exception rather than just the FOSSBilling specific one. I will correct this in the code

File: src/library/FOSSBilling/Instance.php
Comment (BelleNottelling) [reply src/library/FOSSBilling/Instance.php:1]: > I agree it's not the most likely scenario, however an attack may not be quite so complicated if targeted. For example, if someone was to gain access to the Sentry data (via whatever means) it would only take seconds to find all reports related to a particular URL known to be running FOSSBilling (or even the reports for every known FOSSBilling install URL, as it would take seconds/minutes to generate them all).

Indeed, but I don't think the actual method of generating the IDs changes this :P

> I am perfectly happy with either approach, as they solve the issues raised. UUIDv4 is, I understand, practically unique and I highly doubt we would ever run into collisions at our scale. However, to further reduce the risk UUIDv5 with a unique namespace also works for me. 🙂

I understand the risk of a collision is extremely minimal, but I think I'll still go for the v5 option just to be 100% certain

Comment (BelleNottelling) [reply src/library/FOSSBilling/Instance.php:1]: I lied, I looked up just how random UUID v4 IDs are and it was way more than I wrongly assumed. Switched to those instead and they are now stored in the config file

Comment (admdly) [reply src/library/FOSSBilling/Instance.php:1]: > I lied, I looked up just how random UUID v4 IDs are and it was way more than I wrongly assumed. Switched to those instead and they are now stored in the config file

Works for me 😄 - I think chance of getting a collision with UUIDv4 is virtually non-existent for our use case.

File: src/install/install.php [hunk 6]
```diff
@@ -406,17 +419,18 @@ private function install(): bool
...
         // Load default sample config
         $data = require PATH_CONFIG_SAMPLE;
 
         // Handle dynamic configs
-        $data['security']['force_https'] = FOSSBilling\Tools::isHTTPS() ? true : false;
+        $data['security']['force_https'] = FOSSBilling\Tools::isHTTPS();
+        $data['debug_and_monitoring']['report_errors'] = (bool)$this->session->get('error_reporting');
         $data['update_branch'] = $updateBranch;
-        $data['salt'] = md5(random_bytes(13));
+        $data['info']['salt'] = bin2hex(random_bytes(16));
```
Comment (BelleNottelling) [inline src/install/install.php:432]: Just wanted to make note of the change on how the salt is generated from `md5(random_bytes(13));` to `bin2hex(random_bytes(16));`.

It's unrelated to this PR, however I was already making changes on this line and I've wanted to change this for awhile now to be a better method. The new way still produces the same length of a salt as before (not that it matters), but actually has slightly more entropy in it.

File: src/library/FOSSBilling/Instance.php
Comment (BelleNottelling) [reply src/library/FOSSBilling/Instance.php:1]: > virtually non-existent for our use case.

Based on what I found online, it's basically non-existent for all cases:

> Speaking of v4 UUIDs, which contain 122 bits of randomness, the odds of collision between any two is 1 in 2.71 x 1018 Put another way, one would need to generate 1 billion v4 UUIDs per second for 85 years to have a 50% chance of a single collision.

Comment (admdly) [reply src/library/FOSSBilling/Instance.php:1]: > Based on what I found online, it's basically non-existent for all cases:

Indeed, but I've learned to be overly cautious from tempting fate too many times 😛.

**Review by admdly — APPROVED** [review]
@BelleNottelling thanks for the changes and great work! 😄

**Comment by BelleNottelling** [comment]
I've had to drop support for translations on the error page.
It was proving to be problematic in my testing and we can't have the error page being unreliable.

If someone can find a way to get it working reliably that would be great, but otherwise I think we will have to live with that page only being available in English (which is fine, really. It shouldn't be displayed all that often and most browsers have built-in translation tools)

**Comment by BelleNottelling** [comment]
This is now the most up-to-date preview build with error reporting. It incorporates the suggestions by @admdly, has a few additional fixes and improvements, and should better handle errors (mostly during the initial loading process)
 
[FOSSBilling Error Reporting RC3.zip](https://github.com/FOSSBilling/FOSSBilling/files/13173392/FOSSBilling.Error.Reporting.RC3.zip)

**Review by John-S4 — APPROVED** [review]

**Comment by John-S4** [comment]
Woo, there is a lot in this PR, it takes a while just to get through it all without actually writing any of it!

It's great work, and I can't find any issues :)

Regarding the translateability of the error pages, yes they shouldn't be seen very often (preferably never) but I do think it's a bit of an issue, and I personally hate it when I'm looking at anything in one language and then a page (error or not) pops up in another one. Yes this PR should be merged now, but I think that this should be added as an issue and roadmapped for a future release.

**Review by admdly — APPROVED** [review]

**Comment by BelleNottelling** [comment]
> and I personally hate it when I'm looking at anything in one language and then a page (error or not) pops up in another one.

Indeed, but the problem is that it needs to work when FOSSBilling is functional enough for translations to be working and setup, but it also needs to work when we haven't gotten that far. Previously I was able to get that to be the case by defining a "polyfill" for the ``__trans`` function, however with the changes in this PR that started causing errors and I was unable to find a technique to implement it where it wouldn't cause things to break when ``__trans`` wasn't already defined.

One saving grace, however, is that actual translatable exceptions will still be translated if FOSSBilling is able to get past it's initial loading steps & those messages will be visible on the page in their translated state

**Review by evrifaessa — APPROVED** [review]
Looks very nicely done. Thanks for everything.
