### PR TITLE
Prevent deletion of Servers, Hosting Plans and TLDs that have active Products.

### LINKED ISSUE #1491: [Bug] Deleting a Hosting Server will make Orders that were assigned to this Server unusable.
### Describe the bug

When you delete a Hosting Server (F.ex. HestiaCP Server) and there are orders associated with it, these Orders are then broken. 

It's impossible to edit or delete them. 

image

This brings the database into an inconsistent State from which it's impossible to recover for a non-technical user. 

Even for a technical user, it's quite annoying because the server id is inside the serialized json object "config" in client_order.
image

Adding a new server won't re-use the old ID, so the users have no way to fix this state.

### How to reproduce

1. Create Server
2. Create Product with Server 1 
3. Place Client order with product
4. approve the invoice
5. delete the server
6. try to edit the order  

### Expected behavior

I see two possibilities: 

1. The server can't be deleted unless there's no Orders. (I think this was intended, but somehow it was lost) 
2. The server can be deleted, but all Orders on that server will get a new state "No Server Associated" (or similar)

I doubt that we ever want the situation where an order doesn't have a Server, so deleting a Server with active Orders needs to be prohibited imho.

### Screenshots

_No response_

### FOSSBilling version

0.5.5 / built from main

### Module version

_No response_

### Device

_No response_

### Information

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Anuril**
Fixes #1491 

I've started to rework deletion checks so no unintended database issues can arise.

We should really start working with referential integrity, otherwise this will become a lot of code very soon.

That would also benefit from things like Taxes be referred to by their IDs, not their names.

https://github.com/FOSSBilling/FOSSBilling/blob/ad94a9f3255801817f393cda36bc0a38796e1eb9/src/install/sql/structure.sql#L575

https://github.com/FOSSBilling/FOSSBilling/blob/ad94a9f3255801817f393cda36bc0a38796e1eb9/src/install/sql/structure.sql#L1365

### CODE REVIEW

File: src/modules/Client/Api/Admin.php [hunk 1]
```diff
@@ -567,6 +578,14 @@ public function group_delete($data)
 
         $model = $this->di['db']->getExistingModelById('ClientGroup', $data['id'], 'Group not found');
 
+        $clients = $this->di['db']->find('Client', 'client_group_id = :group_id',[':group_id' => $data['id']]);
+
+        $count = count($clients);
```
Comment (BelleNottelling) [inline src/modules/Client/Api/Admin.php:583]: It's minor, but I'd rather just use the count function in the if statement below.
The other cases are fine as-is as they are doing a lot more than just `count($clients)`, though

File: src/modules/Servicedomain/Api/Admin.php [hunk 2]
```diff
@@ -211,6 +213,13 @@ public function tld_delete($data)
         if (!$model instanceof \Model_Tld) {
             throw new \Box_Exception('TLD not found');
         }
+        // check if tld is used by any domain
+        $service_domains = $this->di['db']->find('ServiceDomain', 'tld = ?', ['tld' => $model->tld]);
+        $count = count($service_domains);
+        if ($count > 0) {
+            throw new \Box_Exception('TLD is used by :count: domains', ['count' => $count], 707);
```
Comment (BelleNottelling) [inline src/modules/Servicedomain/Api/Admin.php:220]: You are using the placeholder wrong here. It needs to be `:count:` in both places, not just one

File: src/modules/Servicedomain/Api/Admin.php [hunk 3]
```diff
@@ -344,9 +353,20 @@ public function registrar_delete($data)
...
         $model = $this->di['db']->getExistingModelById('TldRegistrar', $data['id'], 'Registrar not found');
 
+        // check if registrar is used by any domain
+        $service_domains = $this->di['db']->find('ServiceDomain', 'tld_registrar_id = ?', ['tld_registrar_id' => $model->id]);
+
+        // Ensure $service_domains is an array before counting its elements
+        $count = is_array($service_domains) ? count($service_domains) : 0; // Handle the case where $service_domains might be null
+
+        if ($count > 0) {
+            throw new \Box_Exception('Registrar is used by :count: domains', ['count' => $count], 707);
```
Comment (BelleNottelling) [inline src/modules/Servicedomain/Api/Admin.php:363]: You are using the placeholder wrong here. It needs to be `:count:` in both places, not just one

**Review by BelleNottelling — APPROVED** [review]

**Review by jaapmarcus — APPROVED** [review]
